package com.garminconnect

object AppConstants {
  const val KEY_MESSAGE_TYPE = "KEY_MESSAGE_TYPE"
  const val KEY_MESSAGE_PAYLOAD = "KEY_MESSAGE_PAYLOAD"
  const val MESSAGE_PAYLOAD = "MESSAGE_PAYLOAD"

  const val MESSAGE_TYPE_CURRENT_ANGLE = "MESSAGE_TYPE_CURRENT_ANGLE"
  const val MESSAGE_TYPE_MAX_ANGLE = "MESSAGE_TYPE_MAX_ANGLE"

  const val APP_ID = "ae0c9c23-71b8-4285-ab84-a467a096f5c6"

  const val STATUS_ONLINE = "ONLINE"
  const val STATUS_OFFLINE = "OFFLINE"
}
